# Import libraries

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

# Import dataframe

In [2]:
#Importing data set orders_products_merged.pkl
ords_prods_merge = pd.read_pickle('/Users/shailioza/Documents/CareerFoundry Projects/Instacart Basket Analysis/02 Data/Prepared Data/orders_products_merged_2.pkl')

In [3]:
ords_prods_merge.shape

(32404859, 19)

In [4]:
df = ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 19)

In [6]:
df.head()

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day,price_range_loc
0,0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product
1,1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product
2,2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product
3,3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Average orders,Mid-range product
4,4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product

# Grouping data with pandas

In [20]:
# To recap, you should always use the groupby() function as part of a series of steps, namely, the following:

# 1. Split the data into groups based on some criteria.
# 2. Apply a function to each group separately.
# 3. Combine the results into a dataframe or alternative data structure or create a new column in the current dataframe.

# So far, you’ve only completed the first step—splitting the data into groups (with the group being the “product_name” column)

In [7]:
df.groupby('product_name')

# Aggregate data with agg()

In [ ]:
#  If you were to calculate the mean of the “order_number” column grouped by the “department_id” column,
# you could quickly compare the average number of orders across each Instacart department.
# This will involve two of the steps in the three-step process introduced above:

# 1. Split the data into groups based on “department_id.”
# 2. Apply the agg() function to each group to obtain the mean values for the “order_number” column.

In [8]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [9]:
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [10]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

# Aggregate data with transform()

In [ ]:
# Now, let’s map this task onto the three-step process introduced earlier:

# 1. Split the data into groups based on the “user_id” column.
# 2. Apply the transform() function on the “order_number” column to generate the maximum orders for each user.
# 3. Create a new column, “max_order,” into which you’ll place the results of your aggregation.

In [11]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)
# df_orders_products_merged['max_order'] = df_orders_products_merged.groupby(['user_id'])['order_number'].transform(np.max)

# Let’s run through each piece of the code in turn:
# First, a new column called “max_order” is created, which will be what stores the maximum order number for each user (step 3).
# Then, the df_orders_products_merged dataframe is grouped by the “user_id” column (step 1).
# And finally, the transform() function is applied on the “order_number” column with the np.max argument (step 2).

In [12]:
ords_prods_merge.head(100)

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day,price_range_loc,max_order
0,0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,10
1,1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,10
2,2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,10
3,3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Average orders,Mid-range product,10
4,4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5895,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,3
96,6137,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,3
97,6259,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,8
98,6740,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Regularly busy,Busiest days,Average orders,Mid-range product,22
99,6741,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,22

In [13]:
pd.options.display.max_rows = None

In [14]:
ords_prods_merge.head(100)

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day,price_range_loc,max_order
0,0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,10
1,1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,10
2,2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,10
3,3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Average orders,Mid-range product,10
4,4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,10
5,5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,10
6,6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,10
7,7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,10
8,8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,10
9,9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Average orders,Mid-range product,10
10,144,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,22
11,146,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,22
12,147,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,22
13,150,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,22
14,151,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,22
15,209,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,9
16,212,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,9
17,214,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Average orders,Mid-range product,9
18,232,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,33
19,458,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,20
20,465,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,20
21,617,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,11
22,620,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,11
23,751,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27
24,752,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27
25,753,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27
26,755,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27
27,757,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,27
28,759,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27
29,760,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27
30,761,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27
31,762,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27
32,765,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27
33,767,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27
34,768,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27
35,769,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,27
36,771,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27
37,1022,3205960,67,1,3,11,NaN,196,1,0,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,24
38,1023,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
39,1024,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
40,1025,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24
41,1026,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,24
42,1027,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,24
43,1029,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24
44,1030,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24
45,1031,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
46,1032,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
47,1033,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24
48,1034,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
49,1035,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
50,1037,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,24
51,1039,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24
52,1040,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,both,Busiest day,Busiest days,Most orders,Mid-range product,24
53,1042,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
54,1043,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
55,1044,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24
56,1202,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,7
57,1204,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,7
58,1208,1889835,82,1,3,15,NaN,196,6,0,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,19
59,1210,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,19
60,1211,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,both,Busiest day,Busiest days,Most orders,Mid-range product,19
61,1213,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,19
62,1216,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,19
63,1217,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,19
64,1222,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,19
65,1225,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,19
66,1226,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,19
67,1480,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,both,Busiest day,Busiest days,Most orders,Mid-range product,14
68,1484,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,14
69,1486,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,14
70,1488,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,14
71,1489,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,14
72,1490,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,14
73,1491,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,14
74,1608,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,6
75,1744,520620,120,1,3,11,NaN,196,2,0,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,3
76,1746,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,3
77,2781,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,6
78,2891,2040988,195,1,1,14,NaN,196,2,0,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,58
79,2898,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,58
80,2909,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,58
81,2912,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,58
82,2915,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,58
83,2921,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,58
84,2924,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,58
85,2927,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,58
86,2930,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,58
87,2937,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,58
88,2942,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,58
89,2947,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,58
90,3451,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,70
91,3472,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,70
92,4667,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,51
93,4686,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,51
94,5551,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,8
95,5895,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,3
96,6137,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,3
97,6259,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,8
98,6740,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Regularly busy,Busiest days,Average orders,Mid-range product,22
99,6741,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,22

# Deriving Columns with loc()

In [ ]:
# To create your flag, you’ll need some criteria. You can use the following:

# 1. If the maximum orders the user has made is over 40, then the customer will be labeled a “Loyal customer.”
# 2. If the maximum orders the user has made is over 10 but less than or equal to 40, then the customer will be labeled a “Regular customer.”
# 3. If the maximum orders the user has made is less than or equal to 10, then the customer will be labeled a “New customer.”

In [15]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [16]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [17]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [18]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [19]:
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)
# The first set of brackets is the same as the brackets used in df['column'] above,
# while the second set of brackets is indicating that what you’re indexing is a list of multiple columns (and lists are always included within brackets).
# This is why there are two sets of brackets.

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

In [ ]:
# You learned already that to access a single column in a dataframe, you can index it like so: df['column']

# TASK 4.8

In [21]:
# Step 1: Done

In [22]:
# Step 2:
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

Step 3: The means differ as the previous aggregation is conducted on a subset; therefore, only part of the data is used which creates difference in means and fewer numbers of user ids

In [23]:
# Step 4:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [24]:
ords_prods_merge.head(100)

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,busiest_day,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,10,New customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,10,New customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,10,New customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,77,7,9.0,both,Least busy,Slowest days,Average orders,Mid-range product,10,New customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,10,New customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,10,New customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,10,New customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,10,New customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,10,New customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,77,7,9.0,both,Least busy,Slowest days,Average orders,Mid-range product,10,New customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,22,Regular customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,22,Regular customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,22,Regular customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,22,Regular customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,22,Regular customer
15,209,2293453,19,2,5,14,6.0,196,3,0,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,9,New customer
16,212,1973799,19,5,6,12,8.0,196,15,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,9,New customer
17,214,532817,19,7,4,17,6.0,196,1,1,...,77,7,9.0,both,Least busy,Slowest days,Average orders,Mid-range product,9,New customer
18,232,1573906,21,10,3,10,6.0,196,2,0,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,33,Regular customer
19,458,1593000,31,10,3,8,7.0,196,17,0,...,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,20,Regular customer
20,465,2231262,31,17,3,11,8.0,196,14,1,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,20,Regular customer
21,617,2580647,43,6,4,16,4.0,196,9,0,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,11,Regular customer
22,620,2187180,43,9,4,12,3.0,196,1,1,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,11,Regular customer
23,751,2497897,52,1,1,9,NaN,196,4,0,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27,Regular customer
24,752,1318871,52,2,1,10,7.0,196,5,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27,Regular customer
25,753,1261384,52,3,1,10,7.0,196,3,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27,Regular customer
26,755,580568,52,5,2,10,8.0,196,6,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27,Regular customer
27,757,2428073,52,7,2,7,8.0,196,5,1,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,27,Regular customer
28,759,342306,52,9,1,11,7.0,196,5,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27,Regular customer
29,760,1520353,52,10,2,10,8.0,196,4,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27,Regular customer
30,761,2542086,52,11,2,9,7.0,196,3,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27,Regular customer
31,762,944694,52,12,1,16,6.0,196,7,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,27,Regular customer
32,765,1268191,52,15,2,11,8.0,196,3,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27,Regular customer
33,767,1122089,52,17,2,10,6.0,196,4,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27,Regular customer
34,768,1498922,52,18,2,10,14.0,196,6,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27,Regular customer
35,769,180919,52,19,3,8,8.0,196,4,1,...,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,27,Regular customer
36,771,2695875,52,21,5,10,30.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,27,Regular customer
37,1022,3205960,67,1,3,11,NaN,196,1,0,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,24,Regular customer
38,1023,970922,67,2,1,15,5.0,196,2,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
39,1024,596585,67,3,1,13,7.0,196,2,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24,Regular customer
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,24,Regular customer
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,24,Regular customer
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24,Regular customer
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24,Regular customer
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24,Regular customer
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
49,1035,551869,67,14,1,9,7.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
50,1037,768572,67,16,4,10,9.0,196,1,1,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,24,Regular customer
51,1039,150528,67,18,5,16,4.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,24,Regular customer
52,1040,29758,67,19,0,14,9.0,196,2,1,...,77,7,9.0,both,Busiest day,Busiest days,Most orders,Mid-range product,24,Regular customer
53,1042,1558976,67,21,1,9,5.0,196,2,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
54,1043,863974,67,22,1,11,14.0,196,3,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
55,1044,2308399,67,23,1,14,14.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,24,Regular customer
56,1202,2759128,81,3,1,9,14.0,196,2,0,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,7,New customer
57,1204,1812985,81,5,2,20,30.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,7,New customer
58,1208,1889835,82,1,3,15,NaN,196,6,0,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,19,Regular customer
59,1210,499460,82,3,5,10,5.0,196,2,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,19,Regular customer
60,1211,2728456,82,4,0,11,16.0,196,1,1,...,77,7,9.0,both,Busiest day,Busiest days,Most orders,Mid-range product,19,Regular customer
61,1213,2653743,82,6,4,9,13.0,196,5,1,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,19,Regular customer
62,1216,1358880,82,9,1,10,30.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,19,Regular customer
63,1217,343588,82,10,2,11,1.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,19,Regular customer
64,1222,3034663,82,15,2,11,12.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,19,Regular customer
65,1225,147262,82,18,1,13,7.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,19,Regular customer
66,1226,3144004,82,19,2,15,8.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,19,Regular customer
67,1480,2126069,98,3,0,9,25.0,196,7,0,...,77,7,9.0,both,Busiest day,Busiest days,Most orders,Mid-range product,14,Regular customer
68,1484,2210120,98,7,5,14,5.0,196,1,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,14,Regular customer
69,1486,681011,98,9,3,9,30.0,196,1,1,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,14,Regular customer
70,1488,2846344,98,11,4,13,15.0,196,2,1,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,14,Regular customer
71,1489,747431,98,12,6,13,30.0,196,4,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,14,Regular customer
72,1490,2383054,98,13,4,11,30.0,196,1,1,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,14,Regular customer
73,1491,1993729,98,14,5,8,8.0,196,2,1,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,14,Regular customer
74,1608,1403849,109,3,3,17,9.0,196,5,0,...,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,6,New customer
75,1744,520620,120,1,3,11,NaN,196,2,0,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,3,New customer
76,1746,3273029,120,3,2,8,19.0,196,2,1,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,3,New customer
77,2781,1861943,185,2,1,12,25.0,196,10,0,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,6,New customer
78,2891,2040988,195,1,1,14,NaN,196,2,0,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,58,Loyal customer
79,2898,1680569,195,8,1,9,4.0,196,2,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,58,Loyal customer
80,2909,276171,195,19,5,11,3.0,196,2,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,58,Loyal customer
81,2912,2744976,195,22,5,10,7.0,196,2,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,58,Loyal customer
82,2915,2781919,195,25,1,14,4.0,196,1,1,...,77,7,9.0,both,Regularly busy,Busiest days,Most orders,Mid-range product,58,Loyal customer
83,2921,1738718,195,31,2,8,4.0,196,2,1,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,58,Loyal customer
84,2924,3058369,195,34,3,10,6.0,196,2,1,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,58,Loyal customer
85,2927,1485596,195,37,2,15,0.0,196,2,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,58,Loyal customer
86,2930,417035,195,40,3,16,2.0,196,2,1,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,58,Loyal customer
87,2937,1615297,195,47,5,10,2.0,196,2,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,58,Loyal customer
88,2942,1765587,195,52,3,12,2.0,196,3,1,...,77,7,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,58,Loyal customer
89,2947,745908,195,57,4,11,3.0,196,3,1,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,58,Loyal customer
90,3451,2505656,222,17,2,12,1.0,196,2,0,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,70,Loyal customer
91,3472,3268370,222,38,5,15,1.0,196,6,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,70,Loyal customer
92,4667,2016711,290,9,5,19,6.0,196,8,0,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,51,Loyal customer
93,4686,2706088,290,28,6,10,7.0,196,16,1,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,51,Loyal customer
94,5551,1952286,331,6,5,16,30.0,196,8,0,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,8,New customer
95,5895,3226575,360,1,5,12,NaN,196,1,0,...,77,7,9.0,both,Regularly busy,Regularly days,Most orders,Mid-range product,3,New customer
96,6137,1469869,377,3,5,17,3.0,196,9,0,...,77,7,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,3,New customer
97,6259,1927023,387,2,4,10,22.0,196,3,0,...,77,7,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,8,New customer
98,6740,858092,420,4,1,19,30.0,196,2,0,...,77,7,9.0,both,Regularly busy,Busiest days,Average orders,Mid-range product,22,Regular customer
99,6741,119314,420,5,3,19,16.0,196,2,1,...,77,7,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,22,Regular customer

Step 4 : loc() function used in Output 19

In [27]:
# Checking loyalty flag values
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [28]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False).sum()

32404859

In [29]:
ords_prods_merge.shape

(32404859, 21)

In [30]:
# Step 5:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max','sum']})

                     prices
                       mean  min      max          sum
loyalty_flag
Loyal customer    10.386336  1.0  99999.0  106814042.2
New customer      13.294670  1.0  99999.0   83011787.2
Regular customer  12.495717  1.0  99999.0  198391693.2

This is a bit surprising output. The average prices for new customers is highest and loyal customers is lowest. This could be because loyal customers are buying cheaper products. The sum of price paid however is higher for regular customers and loyal customers due to increased number of visits and purchases.

In [31]:
# Step 6:
ords_prods_merge['avg_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [32]:
ords_prods_merge.loc[ords_prods_merge['avg_price'] >= 10, 'spending_flag'] = 'High spender'

In [33]:
ords_prods_merge.loc[ords_prods_merge['avg_price'] < 10, 'spending_flag'] = 'Low spender'

In [34]:
ords_prods_merge.head()

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,prices,_merge,busiest_day,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag,avg_price,spending_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,9.0,both,Regularly busy,Regularly days,Average orders,Mid-range product,10,New customer,6.367797,Low spender
1,1,2398795,1,2,3,7,15.0,196,1,1,...,9.0,both,Regularly busy,Slowest days,Average orders,Mid-range product,10,New customer,6.367797,Low spender
2,2,473747,1,3,3,12,21.0,196,1,1,...,9.0,both,Regularly busy,Slowest days,Most orders,Mid-range product,10,New customer,6.367797,Low spender
3,3,2254736,1,4,4,7,29.0,196,1,1,...,9.0,both,Least busy,Slowest days,Average orders,Mid-range product,10,New customer,6.367797,Low spender
4,4,431534,1,5,4,15,28.0,196,1,1,...,9.0,both,Least busy,Slowest days,Most orders,Mid-range product,10,New customer,6.367797,Low spender

In [35]:
#Checking the count of 'spending_flag' values
ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: spending_flag, dtype: int64

In [36]:
ords_prods_merge['spending_flag'].value_counts(dropna = False).sum()

32404859

In [37]:
ords_prods_merge.shape

(32404859, 23)

In [38]:
# Step 7:
ords_prods_merge['median_freq'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [39]:
ords_prods_merge.loc[ords_prods_merge['median_freq'] > 20, 'order_freq_flag'] = 'Non-frequent customer'

In [40]:
ords_prods_merge.loc[(ords_prods_merge['median_freq'] > 10) & (ords_prods_merge['median_freq'] <= 20), 'order_freq_flag'] = 'Regular customer'

In [41]:
ords_prods_merge.loc[ords_prods_merge['median_freq'] <= 10, 'order_freq_flag'] = 'Frequent customer'

In [42]:
ords_prods_merge.head(15)

,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,busiest_day,busiest_days,busiest_period_of_day,price_range_loc,max_order,loyalty_flag,avg_price,spending_flag,median_freq,order_freq_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,Regularly busy,Regularly days,Average orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,Regularly busy,Slowest days,Average orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,Regularly busy,Slowest days,Most orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,Least busy,Slowest days,Average orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,Least busy,Slowest days,Most orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,Regularly busy,Regularly days,Average orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,Regularly busy,Busiest days,Most orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,Regularly busy,Busiest days,Most orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,Regularly busy,Busiest days,Most orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,Least busy,Slowest days,Average orders,Mid-range product,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,Regularly busy,Busiest days,Most orders,Mid-range product,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,Regularly busy,Regularly days,Most orders,Mid-range product,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,Regularly busy,Regularly days,Most orders,Mid-range product,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,Regularly busy,Busiest days,Most orders,Mid-range product,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,Regularly busy,Busiest days,Most orders,Mid-range product,22,Regular customer,3.980556,Low spender,10.0,Frequent customer

In [43]:
#Checking the count of 'order_freq_flag' values
ords_prods_merge['order_freq_flag'].value_counts(dropna = False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: order_freq_flag, dtype: int64

In [44]:
ords_prods_merge['order_freq_flag'].value_counts(dropna = False).sum()

32404859

In [45]:
# Export the dataframe as a pickle file
ords_prods_merge.to_pickle(r'/Users/shailioza/Documents/CareerFoundry Projects/Instacart Basket Analysis/02 Data/Prepared Data/orders_products_merged_aggregated.pkl')

In [ ]:
# Further data cleaning steps

ords_prods_merge.loc[ords_prods_merge['prices'] >100, 'prices'] = np.nan
ords_prods_merge['prices'].max()